# Site settings
title: Aidan Pasquale
description: IT Specialist | Skier | Motorcyclist | Mountain Biker
# baseurl: "" # the subpath of your site, e.g. /blog
url: "https://aidanpasquale.com" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Aidan Pasquale
user_description: A 21 year old IT specialist, looking to gain a broad knowledge across the technical aspects of the software industry.
user_title: Software Engineer
email: aidanpasquale75@gmail.com
# twitter_username: lorem_ipsum
github_username:  Aidan-Pasquale99
# gplus_username:  lorem_ipsum

exclude: ['package.json', 'src' , 'node_modules']
include:
  - "_img"
