# Site settings
title: Aidan Pasquale
description: IT Specialist | Skier | Motorcyclist
# baseurl: "" # the subpath of your site, e.g. /blog
url: "https://aidanpasquale.com" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Aidan Pasquale
user_description: Principal Cloud, SaaS, Automation, & Containerisation specialist with a First-class BSc in Software Engineering, with seven years of experience in the financial services industry, developing software (AWS Lambda Functions, Spring Boot REST APIs), architecting and owning the AWS & OpenShift stacks, and building a SaaS banking platform running on AWS.
user_title: Software Engineer
email: aidanpasquale75@gmail.com
github_username:  Aidan-Pasquale99

exclude: ['package.json', 'src' , 'node_modules']
