# Site settings
title: Aidan Pasquale
description: IT Specialist | Skier | Motorcyclist
# baseurl: "" # the subpath of your site, e.g. /blog
url: "https://aidanpasquale.com" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Aidan Pasquale
user_description: A 25 year old Cloud, SaaS, Automation, & Containerisation specialist with a First-class BSC in Software Engineering, currently working on building a SaaS banking platform running in the cloud at <a href='https://www.temenos.com'>Temenos</a>.
user_title: Software Engineer
email: aidanpasquale75@gmail.com
github_username:  Aidan-Pasquale99

exclude: ['package.json', 'src' , 'node_modules']
